server:
  port: 9999
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306"
    username: "root"
    password: "admin"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect
